name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      uses: actions/setup-node@v1
      with:
        node-version: '13.12.0'
      run: ./scripts/build.sh
