name: On PR closed - Delete firebase hosting channel
on:
  pull_request:
    types:
      - closed
jobs:
  delete_firebase_channel:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: w9jds/firebase-action@12e7dd1a31239567f9b4d398e6c1dc9f1c6fc70a # v13.28.0
        with:
          # Extracts the full channel name from the PR number and feeds it to the delete command
          args: hosting:channel:list | grep 'pr${{ github.event.pull_request.number }}' | cut --delimeter ' ' --fields 2 | xargs -I {} firebase hosting:channel:delete --force {}
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BVARGA_FE600 }}
          PROJECT_ID: bvarga-fe600