name: deploy

on:
  push:
    branches:
      - 'deploy/**'

jobs:

  build:

    runs-on: ubuntu-18.04
    env:
      ENVIRONMENT: ${{ secrets.ENVIRONMENT}}
      DOCKER_CA: ${{ secrets.DOCKER_CA}}
      DOCKER_CERT: ${{ secrets.DOCKER_CERT}}
      DOCKER_KEY: ${{ secrets.DOCKER_KEY}}
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Setup
      run: ./scripts/before_deploy.sh
    - name: Run Deploy
      run: ./scripts/deploy.sh
    - name: Clean
      if: always()
      run: ./scripts/after_deploy.sh
