name: release

on:
  create:
    tags:
    - '*'

jobs:

  release:

    runs-on: ubuntu-18.04
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
    steps:
    - uses: actions/checkout@v2
    - name: Make release
      uses: actions/setup-node@v1
      with:
        node-version: '13.12.0'
      run: ./scripts/release.sh
