name: release

on:
  push:
    tags:
      - '*'

jobs:

  release:

    runs-on: ubuntu-18.04
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '13.12.0'
    - name: Make release
      run: ./scripts/release.sh
