name: release

on:
  create:
    tags:

jobs:

  release:

    runs-on: ubuntu-18.04
    env:
      ENVIRONMENT: ${{ secrets.ENVIRONMENT}}
      DOCKER_CA: ${{ secrets.DOCKER_CA}}
      DOCKER_CERT: ${{ secrets.DOCKER_CERT}}
      DOCKER_KEY: ${{ secrets.DOCKER_KEY}}
      HOST: ${{ secrets.HOST}}
    steps:
    - uses: actions/checkout@v2
    - name: Make release
      run: ./scripts/release.sh
